language: java
jdk:
- openjdk11
os:
- linux
env:
- PROJECT_DIR=1/ru.hse.anstkras
- PROJECT_DIR=2
- PROJECT_DIR=TreeSet
- PROJECT_DIR=4/PhoneBook
- PROJECT_DIR=Reflector
- PROJECT_DIR=HashTable
- PROJECT_DIR=qsort
- PROJECT_DIR=springTest2
script: 
- if [ -d "$PROJECT_DIR" ]; then
  cd $PROJECT_DIR && ./gradlew check;
  fi
